Create Database LearnersDB;
USE LearnersDB;
Create Table Learnersdata(
 ID INT PRIMARY KEY AUTO_INCREMENT,
 NAME VARCHAR(20),
 AGE INT ,
 DEPARTMENT VARCHAR(20),
CITY VARCHAR(20),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
               ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO Learnersdata(ID, NAME, AGE,DEPARTMENT,CITY)VALUES('1','RENITA',20,'IT','CHENNAI'); 
INSERT INTO Learnersdata(ID, NAME, AGE,DEPARTMENT,CITY)VALUES('2','RENISHA',22,'CSE','BANGLORE'); 
INSERT INTO Learnersdata(ID, NAME, AGE,DEPARTMENT,CITY)VALUES('3','RESHMA',26,'CA','COIMBATORE'); 
INSERT INTO Learnersdata(ID, NAME, AGE,DEPARTMENT,CITY)VALUES('4','RICHIE',23,'CS','HYDERABAD'); 
INSERT INTO Learnersdata(ID, NAME, AGE,DEPARTMENT,CITY)VALUES('5','SHEEBA',24,'IT','KOCHI'); 

UPDATE Learnersdata SET city = 'Bangalore' WHERE ID = 1;
UPDATE Learnersdata SET CITY = 'CHENNAI' WHERE ID = 2;
UPDATE Learnersdata SET AGE = '26' WHERE ID = 4;
UPDATE Learnersdata SET DEPARTMENT = 'PSYCHO' WHERE ID = 5;

 DELETE FROM Learnersdata WHERE id = 5; 


